name: My Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set secret as env var
        env:
          REACT_APP_API_KEY: ${{ secrets.AUTH_SEARCH_REPOS }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Deploy
        run: |
          npm ci
          git config --global user.email "nymtmn8690@gmail.com"
          git config --global user.name "nym_tmn"
          npm run deploy
