name: My Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set secret as env var
        run: |
          echo "MY_TOKEN=${secrets.MY_TOKEN}" >> $GITHUB_ENV

      - name: Run script
        run: |
          echo "My token is: $MY_TOKEN"
